export const MOCK_RESPONSE = {
  id: "31369",
  name: "31369",
  onlinepayment: 2,
  deadline: 1760126400,
  openline: 1756702800,
  openline_club: 0,
  truedeadline: 1760126400,
  canregister: true,
  status: 0,
  isregiopen: true,
  isregiclose: false,
  firstday: 1761343200,
  lastday: 1761519599,
  docs: [],
  regi_nosingledouble: 0,
  regi_nosinglemixed: 1,
  regi_nodoublemixed: 0,
  organizer: "badminton associatif choperais",
  shuttle: "yonex AS20",
  place: {
    location: "Cholet",
    convocplace: null,
    dpt: 0,
    sporthalls: [],
  },
  type: {
    id: 70,
    isteam: false,
    name: "Tournoi individuel",
  },
  level: {
    id: 431,
    name: "Régional",
  },
  maxplayer: 250,
  nbrmaxdraw: 2,
  isfav: false,
  isregistered: 0,
  comment:
    "Bonjour à tous,\n \nNous sommes très heureux de vous convier à notre édition de l'OCTOBACH 2025 de Cholet.\n \nLe tournoi est ouvert aux joueur(se)s classés de R4 à P10 et des catégories de U15 (minimes) à vétérans.\n \nDATES ET TABLEAUX \n \nSamedi 25 octobre : simples hommes et dames et doubles mixtes.\n \nDimanche 26 octobre : doubles hommes et dames.\n \nInterdit de s'inscrire sur les tableaux de simple et de mixte.\n \nINSCRIPTIONS\n \nDébut des inscriptions le 1 septembre.\n \nFin des inscriptions le 10 octobre en fonction du nombre de place disponible.\n \nTarifs : 15€ pour 1 tableau et 20€ pour 2 tableaux.\n \nInscription uniquement via BADNET ou EBAD.\n \nLes inscriptions seront validées après le paiement des joueur(se)s. Si inscription sur tableau de double/mixte, inscription validée quand le deuxième joueur(se) à réglé.\n \nLIEU DE LA COMPÉTITION\n \nComplexe Auguste Grégoire, 41 rue Maurice Ravel, 49300 CHOLET.\n \nRESTAURATION\n \nComme toujours, notre buvette seront à votre disposition avec différents choix froid ou chaud, pour tous (paninis, boissons, sandwichs, ...).\n \nCONTACTS\n \nGEO: Adeline BOUZY = adeline.bach49@gmail.com ou 0622030944\n \nJuges Arbitres: BENOIT Frédéric et VAISSIER Jean Guy.\n \n\n \n Mail organisateur : adeline.bach49@gmail.com",
  lastnews:
    "<p>Bonjour à tous,</p><p>Nous sommes très heureux de vous convier à notre édition de l'OCTOBACH 2025 de Cholet.</p><p>Le tournoi est ouvert aux joueur(se)s classés de R4 à P10 et des catégories de U15 (minimes) à vétérans.</p><p><u>DATES ET TABLEAUX&nbsp;</u></p><p>Samedi 25 octobre : simples hommes et dames et doubles mixtes.</p><p>Dimanche 26 octobre : doubles hommes et dames.</p><p>Interdit de s'inscrire sur les tableaux de simple et de mixte.</p><p><u>INSCRIPTIONS</u></p><p>Début des inscriptions le 1 septembre.</p><p>Fin des inscriptions le 10 octobre en fonction du nombre de place disponible.</p><p>Tarifs : 15€ pour 1 tableau et 20€ pour 2 tableaux.</p><p>Inscription uniquement via BADNET ou EBAD.</p><p>Les inscriptions seront validées après le paiement des joueur(se)s. Si inscription sur tableau de double/mixte, inscription validée quand le deuxième joueur(se) à réglé.</p><p><u>LIEU DE LA COMPÉTITION</u></p><p>Complexe Auguste Grégoire, 41 rue Maurice Ravel, 49300 CHOLET.</p><p><u>RESTAURATION</u></p><p>Comme toujours, notre buvette seront à votre disposition avec différents choix froid ou chaud, pour tous (paninis, boissons, sandwichs, ...).</p><p><u>CONTACTS</u></p><p>GEO: Adeline BOUZY = <a href=\"mailto:adeline.bach49@gmail.com\">adeline.bach49@gmail.com</a> ou 0622030944</p><p>Juges Arbitres: BENOIT Frédéric et VAISSIER Jean Guy.</p>",
  info: "Bonjour à tous,\r\nComme vous le savez, le classement nouvelle formule sera effectif à partir d'aujourd'hui.\r\nLes mises à jour se font donc aujourd'hui pour Badnet, Ebad, MyFFBAD et Poona.\r\nC'est pourquoi, les inscriptions ne peuvent se faire aujourd'hui. Désolé pour la gêne occasionnée.\r\n(message de la fédération).\r\nPas besoin d'envoyer de message pour vous inscrire, tout reviendra dans l'ordre demain.\r\nBonne journée à tous(tes).\r\nAdeline et Romain",
  visitors: 392,
  website: null,
  urlaffiche: "https://badnet.fr/Img/poster/affiche_default.png",
  pointsmin: 0,
  pointsmax: 0,
  isbuvette: false,
  draws: [
    {
      id: "726012",
      eventid: "31369",
      name: "Simple Homme S3",
      serial: "Série 3",
      discipline: {
        id: 1,
        isdouble: false,
        name: "Simple homme",
        stamp: "SH",
      },
      mincatage: {
        id: 303,
        name: "Minime",
        nameshort: "Minime",
      },
      maxcatage: {
        id: 317,
        name: "Vétéran 10",
        nameshort: "Vétéran 10",
      },
      catage: {
        id: 303,
        name: "Minime",
        nameshort: "Minime",
      },
      minpoint: 0,
      maxpoint: 0,
      minrank: 0,
      maxrank: 0,
      minranking: {
        name: "P10",
        id: 113,
        system: 323,
        minpoint: 2.75,
        minrank: 39141,
        maxpoint: 6,
        maxrank: 26180,
      },
      maxranking: {
        name: "D8",
        id: 111,
        system: 323,
        minpoint: 11.08,
        minrank: 13509,
        maxpoint: 18.02,
        maxrank: 8718,
      },
      isclose: false,
      stamp: "SH S3",
      fees: 0,
    },
    {
      id: "726013",
      eventid: "31369",
      name: "Simple Dame",
      serial: "Série 3",
      discipline: {
        id: 2,
        isdouble: false,
        name: "Simple dame",
        stamp: "SD",
      },
      mincatage: {
        id: 303,
        name: "Minime",
        nameshort: "Minime",
      },
      maxcatage: {
        id: 317,
        name: "Vétéran 10",
        nameshort: "Vétéran 10",
      },
      catage: {
        id: 303,
        name: "Minime",
        nameshort: "Minime",
      },
      minpoint: 0,
      maxpoint: 0,
      minrank: 0,
      maxrank: 0,
      minranking: {
        name: "P10",
        id: 113,
        system: 323,
        minpoint: 3,
        minrank: 19587,
        maxpoint: 7.08,
        maxrank: 13113,
      },
      maxranking: {
        name: "D8",
        id: 111,
        system: 323,
        minpoint: 18.55,
        minrank: 6772,
        maxpoint: 46.13,
        maxrank: 4371,
      },
      isclose: false,
      stamp: "SD S3",
      fees: 0,
    },
    {
      id: "726014",
      eventid: "31369",
      name: "Double Homme",
      serial: "Série 3",
      discipline: {
        id: 3,
        isdouble: true,
        name: "Double homme",
        stamp: "DH",
      },
      mincatage: {
        id: 303,
        name: "Minime",
        nameshort: "Minime",
      },
      maxcatage: {
        id: 317,
        name: "Vétéran 10",
        nameshort: "Vétéran 10",
      },
      catage: {
        id: 303,
        name: "Minime",
        nameshort: "Minime",
      },
      minpoint: 0,
      maxpoint: 0,
      minrank: 0,
      maxrank: 0,
      minranking: {
        name: "P10",
        id: 113,
        system: 323,
        minpoint: 2.66,
        minrank: 39210,
        maxpoint: 6.78,
        maxrank: 26161,
      },
      maxranking: {
        name: "D8",
        id: 111,
        system: 323,
        minpoint: 12.05,
        minrank: 13508,
        maxpoint: 20.55,
        maxrank: 8719,
      },
      isclose: false,
      stamp: "DH S3",
      fees: 0,
    },
    {
      id: "726015",
      eventid: "31369",
      name: "Double Dame",
      serial: "Série 3",
      discipline: {
        id: 4,
        isdouble: true,
        name: "Double dame",
        stamp: "DD",
      },
      mincatage: {
        id: 303,
        name: "Minime",
        nameshort: "Minime",
      },
      maxcatage: {
        id: 317,
        name: "Vétéran 10",
        nameshort: "Vétéran 10",
      },
      catage: {
        id: 303,
        name: "Minime",
        nameshort: "Minime",
      },
      minpoint: 0,
      maxpoint: 0,
      minrank: 0,
      maxrank: 0,
      minranking: {
        name: "P10",
        id: 113,
        system: 323,
        minpoint: 3.75,
        minrank: 19627,
        maxpoint: 9.43,
        maxrank: 13115,
      },
      maxranking: {
        name: "D8",
        id: 111,
        system: 323,
        minpoint: 35.03,
        minrank: 6773,
        maxpoint: 108.93,
        maxrank: 4371,
      },
      isclose: false,
      stamp: "DD S3",
      fees: 0,
    },
    {
      id: "726016",
      eventid: "31369",
      name: "Mixte",
      serial: "Série 3",
      discipline: {
        id: 5,
        isdouble: true,
        name: "Mixte",
        stamp: "MX",
      },
      mincatage: {
        id: 303,
        name: "Minime",
        nameshort: "Minime",
      },
      maxcatage: {
        id: 317,
        name: "Vétéran 10",
        nameshort: "Vétéran 10",
      },
      catage: {
        id: 303,
        name: "Minime",
        nameshort: "Minime",
      },
      minpoint: 0,
      maxpoint: 0,
      minrank: 0,
      maxrank: 0,
      minranking: {
        name: "P10",
        id: 113,
        system: 323,
        minpoint: 2,
        minrank: 34938,
        maxpoint: 4.62,
        maxrank: 21428,
      },
      maxranking: {
        name: "D8",
        id: 111,
        system: 323,
        minpoint: 11.56,
        minrank: 10594,
        maxpoint: 24.82,
        maxrank: 6724,
      },
      isclose: false,
      stamp: "MX S3",
      fees: 0,
    },
    {
      id: "729193",
      eventid: "31369",
      name: "Simple Homme Série 1",
      serial: "Série 1",
      discipline: {
        id: 1,
        isdouble: false,
        name: "Simple homme",
        stamp: "SH",
      },
      mincatage: {
        id: 303,
        name: "Minime",
        nameshort: "Minime",
      },
      maxcatage: {
        id: 317,
        name: "Vétéran 10",
        nameshort: "Vétéran 10",
      },
      catage: {
        id: 303,
        name: "Minime",
        nameshort: "Minime",
      },
      minpoint: 0,
      maxpoint: 0,
      minrank: 0,
      maxrank: 0,
      minranking: {
        name: "R5",
        id: 108,
        system: 323,
        minpoint: 77.45,
        minrank: 3487,
        maxpoint: 168.56,
        maxrank: 2093,
      },
      maxranking: {
        name: "R4",
        id: 107,
        system: 323,
        minpoint: 168.6,
        minrank: 2092,
        maxpoint: 365.32,
        maxrank: 1221,
      },
      isclose: false,
      stamp: "SH S1",
      fees: 0,
    },
    {
      id: "729194",
      eventid: "31369",
      name: "Simple Dame Série 1",
      serial: "Série 1",
      discipline: {
        id: 2,
        isdouble: false,
        name: "Simple dame",
        stamp: "SD",
      },
      mincatage: {
        id: 303,
        name: "Minime",
        nameshort: "Minime",
      },
      maxcatage: {
        id: 317,
        name: "Vétéran 10",
        nameshort: "Vétéran 10",
      },
      catage: {
        id: 303,
        name: "Minime",
        nameshort: "Minime",
      },
      minpoint: 0,
      maxpoint: 0,
      minrank: 0,
      maxrank: 0,
      minranking: {
        name: "R6",
        id: 109,
        system: 323,
        minpoint: 108.27,
        minrank: 2884,
        maxpoint: 259.4,
        maxrank: 1749,
      },
      maxranking: {
        name: "R4",
        id: 107,
        system: 323,
        minpoint: 545.03,
        minrank: 1049,
        maxpoint: 1085.41,
        maxrank: 613,
      },
      isclose: false,
      stamp: "SD S1",
      fees: 0,
    },
    {
      id: "729195",
      eventid: "31369",
      name: "Double Homme Série 1",
      serial: "Série 1",
      discipline: {
        id: 3,
        isdouble: true,
        name: "Double homme",
        stamp: "DH",
      },
      mincatage: {
        id: 303,
        name: "Minime",
        nameshort: "Minime",
      },
      maxcatage: {
        id: 317,
        name: "Vétéran 10",
        nameshort: "Vétéran 10",
      },
      catage: {
        id: 303,
        name: "Minime",
        nameshort: "Minime",
      },
      minpoint: 0,
      maxpoint: 0,
      minrank: 0,
      maxrank: 0,
      minranking: {
        name: "R5",
        id: 108,
        system: 323,
        minpoint: 98.68,
        minrank: 3486,
        maxpoint: 212.96,
        maxrank: 2093,
      },
      maxranking: {
        name: "R4",
        id: 107,
        system: 323,
        minpoint: 213.15,
        minrank: 2092,
        maxpoint: 423.23,
        maxrank: 1221,
      },
      isclose: false,
      stamp: "DH S1",
      fees: 0,
    },
    {
      id: "729196",
      eventid: "31369",
      name: "Double Dame Série 1",
      serial: "Série 1",
      discipline: {
        id: 4,
        isdouble: true,
        name: "Double dame",
        stamp: "DD",
      },
      mincatage: {
        id: 303,
        name: "Minime",
        nameshort: "Minime",
      },
      maxcatage: {
        id: 317,
        name: "Vétéran 10",
        nameshort: "Vétéran 10",
      },
      catage: {
        id: 303,
        name: "Minime",
        nameshort: "Minime",
      },
      minpoint: 0,
      maxpoint: 0,
      minrank: 0,
      maxrank: 0,
      minranking: {
        name: "R5",
        id: 108,
        system: 323,
        minpoint: 730.79,
        minrank: 1748,
        maxpoint: 1601.43,
        maxrank: 1050,
      },
      maxranking: {
        name: "R4",
        id: 107,
        system: 323,
        minpoint: 1602.62,
        minrank: 1049,
        maxpoint: 3071.06,
        maxrank: 613,
      },
      isclose: false,
      stamp: "DD S1",
      fees: 0,
    },
    {
      id: "729197",
      eventid: "31369",
      name: "Mixte Série 1",
      serial: "Série 1",
      discipline: {
        id: 5,
        isdouble: true,
        name: "Mixte",
        stamp: "MX",
      },
      mincatage: {
        id: 303,
        name: "Minime",
        nameshort: "Minime",
      },
      maxcatage: {
        id: 317,
        name: "Vétéran 10",
        nameshort: "Vétéran 10",
      },
      catage: {
        id: 303,
        name: "Minime",
        nameshort: "Minime",
      },
      minpoint: 0,
      maxpoint: 0,
      minrank: 0,
      maxrank: 0,
      minranking: {
        name: "R5",
        id: 108,
        system: 323,
        minpoint: 179.39,
        minrank: 2580,
        maxpoint: 405.35,
        maxrank: 1524,
      },
      maxranking: {
        name: "R4",
        id: 107,
        system: 323,
        minpoint: 405.92,
        minrank: 1523,
        maxpoint: 816.06,
        maxrank: 864,
      },
      isclose: false,
      stamp: "MX S1",
      fees: 0,
    },
    {
      id: "729201",
      eventid: "31369",
      name: "Simple Homme Série 2",
      serial: "Série 2",
      discipline: {
        id: 1,
        isdouble: false,
        name: "Simple homme",
        stamp: "SH",
      },
      mincatage: {
        id: 303,
        name: "Minime",
        nameshort: "Minime",
      },
      maxcatage: {
        id: 317,
        name: "Vétéran 10",
        nameshort: "Vétéran 10",
      },
      catage: {
        id: 303,
        name: "Minime",
        nameshort: "Minime",
      },
      minpoint: 0,
      maxpoint: 0,
      minrank: 0,
      maxrank: 0,
      minranking: {
        name: "D8",
        id: 111,
        system: 323,
        minpoint: 11.08,
        minrank: 13509,
        maxpoint: 18.02,
        maxrank: 8718,
      },
      maxranking: {
        name: "R6",
        id: 109,
        system: 323,
        minpoint: 33.69,
        minrank: 5752,
        maxpoint: 77.43,
        maxrank: 3488,
      },
      isclose: false,
      stamp: "SH S2",
      fees: 0,
    },
    {
      id: "729202",
      eventid: "31369",
      name: "Simple Dame Série 2",
      serial: "Série 2",
      discipline: {
        id: 2,
        isdouble: false,
        name: "Simple dame",
        stamp: "SD",
      },
      mincatage: {
        id: 303,
        name: "Minime",
        nameshort: "Minime",
      },
      maxcatage: {
        id: 317,
        name: "Vétéran 10",
        nameshort: "Vétéran 10",
      },
      catage: {
        id: 303,
        name: "Minime",
        nameshort: "Minime",
      },
      minpoint: 0,
      maxpoint: 0,
      minrank: 0,
      maxrank: 0,
      minranking: {
        name: "D9",
        id: 112,
        system: 323,
        minpoint: 7.09,
        minrank: 13099,
        maxpoint: 18.54,
        maxrank: 6777,
      },
      maxranking: {
        name: "R6",
        id: 109,
        system: 323,
        minpoint: 108.27,
        minrank: 2884,
        maxpoint: 259.4,
        maxrank: 1749,
      },
      isclose: false,
      stamp: "SD S2",
      fees: 0,
    },
    {
      id: "729203",
      eventid: "31369",
      name: "Double Homme Série 2",
      serial: "Série 2",
      discipline: {
        id: 3,
        isdouble: true,
        name: "Double homme",
        stamp: "DH",
      },
      mincatage: {
        id: 303,
        name: "Minime",
        nameshort: "Minime",
      },
      maxcatage: {
        id: 317,
        name: "Vétéran 10",
        nameshort: "Vétéran 10",
      },
      catage: {
        id: 303,
        name: "Minime",
        nameshort: "Minime",
      },
      minpoint: 0,
      maxpoint: 0,
      minrank: 0,
      maxrank: 0,
      minranking: {
        name: "D8",
        id: 111,
        system: 323,
        minpoint: 12.05,
        minrank: 13508,
        maxpoint: 20.55,
        maxrank: 8719,
      },
      maxranking: {
        name: "R6",
        id: 109,
        system: 323,
        minpoint: 41.37,
        minrank: 5753,
        maxpoint: 98.65,
        maxrank: 3488,
      },
      isclose: false,
      stamp: "DH S2",
      fees: 0,
    },
    {
      id: "729204",
      eventid: "31369",
      name: "Double Dame Série 2",
      serial: "Série 2",
      discipline: {
        id: 4,
        isdouble: true,
        name: "Double dame",
        stamp: "DD",
      },
      mincatage: {
        id: 303,
        name: "Minime",
        nameshort: "Minime",
      },
      maxcatage: {
        id: 317,
        name: "Vétéran 10",
        nameshort: "Vétéran 10",
      },
      catage: {
        id: 303,
        name: "Minime",
        nameshort: "Minime",
      },
      minpoint: 0,
      maxpoint: 0,
      minrank: 0,
      maxrank: 0,
      minranking: {
        name: "D8",
        id: 111,
        system: 323,
        minpoint: 35.03,
        minrank: 6773,
        maxpoint: 108.93,
        maxrank: 4371,
      },
      maxranking: {
        name: "R6",
        id: 109,
        system: 323,
        minpoint: 285.6,
        minrank: 2884,
        maxpoint: 730.78,
        maxrank: 1749,
      },
      isclose: false,
      stamp: "DD S2",
      fees: 0,
    },
    {
      id: "729205",
      eventid: "31369",
      name: "Mixte Série 2",
      serial: "Série 2",
      discipline: {
        id: 5,
        isdouble: true,
        name: "Mixte",
        stamp: "MX",
      },
      mincatage: {
        id: 303,
        name: "Minime",
        nameshort: "Minime",
      },
      maxcatage: {
        id: 317,
        name: "Vétéran 10",
        nameshort: "Vétéran 10",
      },
      catage: {
        id: 303,
        name: "Minime",
        nameshort: "Minime",
      },
      minpoint: 0,
      maxpoint: 0,
      minrank: 0,
      maxrank: 0,
      minranking: {
        name: "D8",
        id: 111,
        system: 323,
        minpoint: 11.56,
        minrank: 10594,
        maxpoint: 24.82,
        maxrank: 6724,
      },
      maxranking: {
        name: "R6",
        id: 109,
        system: 323,
        minpoint: 62.28,
        minrank: 4337,
        maxpoint: 179.3,
        maxrank: 2581,
      },
      isclose: false,
      stamp: "MX S2",
      fees: 0,
    },
  ],
  isliveregistration: true,
  regideptnumber: -1,
  regiligueid: -1,
  regiassoid: -1,
  catages: [
    {
      id: "306",
      name: "Sénior",
      nameshort: "Sénior",
    },
  ],
  disciplines: ["SH", "SD", "DH", "DD", "MX"],
  onlylicenced: true,
  publicschedule: 8,
  publicplayers: 2,
  publicdraws: 8,
  publicconvoc: 8,
  publicregi: 2,
  isliveupdate: true,
  deptnumber: 49,
  ligueid: 21,
  mailorga: "adeline.bach49@gmail.com",
  ispromoted: true,
  ageCategories: ["Sénior"],
  firstDay: 1761343200,
  lastDay: 1761519599,
  location: "Cholet",
}
