export const MOCK_RESPONSE = {
  id: "31568",
  name: "Eco-Tournoi de la Grande Horloge",
  onlinepayment: 2,
  deadline: 1763679540,
  openline: 1759341600,
  openline_club: 0,
  truedeadline: 1763679540,
  canregister: false,
  status: 0,
  isregiopen: false,
  isregiclose: false,
  firstday: 1766185200,
  lastday: 1766357999,
  docs: [],
  regi_nosingledouble: 0,
  regi_nosinglemixed: 1,
  regi_nodoublemixed: 0,
  organizer: "Les Volants De Cergy",
  shuttle: "RSL TOURNEY 3",
  place: {
    location: "Cergy",
    convocplace: null,
    dpt: 0,
    sporthalls: [],
  },
  type: { id: 70, isteam: false, name: "Tournoi individuel" },
  level: { id: 433, name: "International" },
  maxplayer: 433,
  nbrmaxdraw: 2,
  isfav: false,
  isregistered: 0,
  comment:
    "*** Ouverture des inscriptions le 1er Octobre en cours de soirée ***\n \n\n \nLe Badminton club Les Volants de Cergy est heureux de vous accueillir pour sa nouvelle édition de son \"Eco-tournoi de la grande horloge\" !!!\n \nInscription en mode standard par ordre d'arrivée et pour les doubles : prise en compte une fois la paire complète inscrite (date de paiement)Simples et Mixtes le samedi (combinaison Simple + Mixte interdite)Doubles le dimanche2 sortants par pouleClassement autorisé de NC jusqu'à R4 inclus. Minime à Vétérans.Ecart entre paires : 2 classements max (ex : R6-D8 autorisé, mais R6-D9 interdit)Complément d'informations dans le règlement particulier du tournoi Pour les petites et grandes faims, une super buvette avec produits frais et bio et une équipe de bénévole toujours au top !\n \n\n \nNotre partenaire DLM Sport sera disponible tout le week-end pour le cordage et la vente de matériel  \n \nParking disponible et accessibilité en transport en commun (RER-A Cergy Préfecture - Bus 1230 arrêt : Les Bocages)\n \nMerci de nous aider dans notre démarche Eco Responsable (Label ECOBAD) avec le co-voiturage et le tri des déchets\n \nPour toute question sur les inscriptions, merci de privilégier l'adresse mail du tournoi : tournoigrandehorloge@gmail.com\n \nA très bientôt !\n \n\n \n Mail organisateur : tournoigrandehorloge@gmail.com",
  lastnews:
    "<p><i><strong>*** Ouverture des inscriptions le 1<sup>er</sup> Octobre en cours de soirée ***</strong></i><br><br>Le Badminton club Les Volants de Cergy est heureux de vous accueillir pour sa nouvelle édition de son&nbsp;\"Eco-tournoi de la grande horloge\" !!!</p><ul style=\"list-style-type:disc;\"><li>Inscription en mode standard par ordre d'arrivée et pour les doubles : prise en compte une fois la paire complète inscrite (date de paiement)</li><li>Simples et Mixtes le samedi (combinaison Simple + Mixte interdite)</li><li>Doubles le dimanche</li><li>2 sortants par poule</li><li>Classement autorisé de NC jusqu'à R4 inclus. Minime à Vétérans.</li><li>Ecart entre paires : 2 classements&nbsp;max&nbsp;(ex : R6-D8 autorisé, mais R6-D9 interdit)</li><li>Complément d'informations dans le règlement particulier du tournoi&nbsp;</li></ul><p>Pour les petites et grandes faims, une super buvette avec produits frais et bio et une équipe de bénévole toujours au top !<br><br>Notre partenaire DLM Sport sera disponible tout le week-end&nbsp;pour le cordage et la vente de matériel&nbsp;&nbsp;</p><p>Parking disponible&nbsp;et accessibilité en&nbsp;transport en commun (RER-A Cergy Préfecture - Bus 1230 arrêt : Les Bocages)<br>Merci de nous aider dans notre démarche Eco Responsable (Label ECOBAD) avec&nbsp;le co-voiturage et le tri des déchets</p><p>Pour toute question sur les inscriptions, merci de privilégier l'adresse mail du tournoi : tournoigrandehorloge@gmail.com</p><p>A très bientôt !</p>",
  info: "",
  visitors: 344,
  website: null,
  urlaffiche: "https://badnet.fr/Img/poster/affiche_default.png",
  pointsmin: 0,
  pointsmax: 0,
  isbuvette: false,
  draws: [
    {
      id: "727652",
      eventid: "31568",
      name: "Simple Homme oui",
      serial: "Oui",
      discipline: {
        id: 1,
        isdouble: false,
        name: "Simple homme",
        stamp: "SH",
      },
      mincatage: { id: 303, name: "Minime", nameshort: "Minime" },
      maxcatage: {
        id: 317,
        name: "Vétéran 10",
        nameshort: "Vétéran 10",
      },
      catage: { id: 303, name: "Minime", nameshort: "Minime" },
      minpoint: 0,
      maxpoint: 0,
      minrank: 0,
      maxrank: 0,
      minranking: {
        name: "NC",
        id: 116,
        system: 323,
        minpoint: 0,
        minrank: 999000,
        maxpoint: 0,
        maxrank: 200000,
      },
      maxranking: {
        name: "R4",
        id: 107,
        system: 323,
        minpoint: 168.6,
        minrank: 2092,
        maxpoint: 365.32,
        maxrank: 1221,
      },
      isclose: false,
      stamp: "SH oui",
      fees: 0,
    },
    {
      id: "727653",
      eventid: "31568",
      name: "Simple Dame oui",
      serial: "Oui",
      discipline: {
        id: 2,
        isdouble: false,
        name: "Simple dame",
        stamp: "SD",
      },
      mincatage: { id: 303, name: "Minime", nameshort: "Minime" },
      maxcatage: {
        id: 317,
        name: "Vétéran 10",
        nameshort: "Vétéran 10",
      },
      catage: { id: 303, name: "Minime", nameshort: "Minime" },
      minpoint: 0,
      maxpoint: 0,
      minrank: 0,
      maxrank: 0,
      minranking: {
        name: "NC",
        id: 116,
        system: 323,
        minpoint: 0,
        minrank: 999000,
        maxpoint: 0,
        maxrank: 200000,
      },
      maxranking: {
        name: "R4",
        id: 107,
        system: 323,
        minpoint: 545.03,
        minrank: 1049,
        maxpoint: 1085.41,
        maxrank: 613,
      },
      isclose: false,
      stamp: "SD oui",
      fees: 0,
    },
    {
      id: "727654",
      eventid: "31568",
      name: "Double Homme oui",
      serial: "Oui",
      discipline: {
        id: 3,
        isdouble: true,
        name: "Double homme",
        stamp: "DH",
      },
      mincatage: { id: 303, name: "Minime", nameshort: "Minime" },
      maxcatage: {
        id: 317,
        name: "Vétéran 10",
        nameshort: "Vétéran 10",
      },
      catage: { id: 303, name: "Minime", nameshort: "Minime" },
      minpoint: 0,
      maxpoint: 0,
      minrank: 0,
      maxrank: 0,
      minranking: {
        name: "NC",
        id: 116,
        system: 323,
        minpoint: 0,
        minrank: 999000,
        maxpoint: 0,
        maxrank: 200000,
      },
      maxranking: {
        name: "R4",
        id: 107,
        system: 323,
        minpoint: 213.15,
        minrank: 2092,
        maxpoint: 423.23,
        maxrank: 1221,
      },
      isclose: false,
      stamp: "DH oui",
      fees: 0,
    },
    {
      id: "727655",
      eventid: "31568",
      name: "Double Dame oui",
      serial: "Oui",
      discipline: {
        id: 4,
        isdouble: true,
        name: "Double dame",
        stamp: "DD",
      },
      mincatage: { id: 303, name: "Minime", nameshort: "Minime" },
      maxcatage: {
        id: 317,
        name: "Vétéran 10",
        nameshort: "Vétéran 10",
      },
      catage: { id: 303, name: "Minime", nameshort: "Minime" },
      minpoint: 0,
      maxpoint: 0,
      minrank: 0,
      maxrank: 0,
      minranking: {
        name: "NC",
        id: 116,
        system: 323,
        minpoint: 0,
        minrank: 999000,
        maxpoint: 0,
        maxrank: 200000,
      },
      maxranking: {
        name: "R4",
        id: 107,
        system: 323,
        minpoint: 1602.62,
        minrank: 1049,
        maxpoint: 3071.06,
        maxrank: 613,
      },
      isclose: false,
      stamp: "DD oui",
      fees: 0,
    },
    {
      id: "727656",
      eventid: "31568",
      name: "Mixte oui",
      serial: "Oui",
      discipline: {
        id: 5,
        isdouble: true,
        name: "Mixte",
        stamp: "MX",
      },
      mincatage: { id: 303, name: "Minime", nameshort: "Minime" },
      maxcatage: {
        id: 317,
        name: "Vétéran 10",
        nameshort: "Vétéran 10",
      },
      catage: { id: 303, name: "Minime", nameshort: "Minime" },
      minpoint: 0,
      maxpoint: 0,
      minrank: 0,
      maxrank: 0,
      minranking: {
        name: "NC",
        id: 116,
        system: 323,
        minpoint: 0,
        minrank: 999000,
        maxpoint: 0,
        maxrank: 200000,
      },
      maxranking: {
        name: "R4",
        id: 107,
        system: 323,
        minpoint: 405.92,
        minrank: 1523,
        maxpoint: 816.06,
        maxrank: 864,
      },
      isclose: false,
      stamp: "MX oui",
      fees: 0,
    },
  ],
  isliveregistration: true,
  regideptnumber: -1,
  regiligueid: -1,
  regiassoid: -1,
  catages: [{ id: "306", name: "Sénior", nameshort: "Sénior" }],
  disciplines: [
    { id: "1", isdouble: false, name: "Simple homme", stamp: "SH" },
    { id: "2", isdouble: false, name: "Simple dame", stamp: "SD" },
    { id: "3", isdouble: true, name: "Double homme", stamp: "DH" },
    { id: "4", isdouble: true, name: "Double dame", stamp: "DD" },
    { id: "5", isdouble: true, name: "Mixte", stamp: "MX" },
  ],
  onlylicenced: true,
  publicschedule: 4,
  publicplayers: 2,
  publicdraws: 8,
  publicconvoc: 4,
  publicregi: 2,
  isliveupdate: true,
  deptnumber: 95,
  ligueid: 12,
  mailorga: "tournoigrandehorloge@gmail.com",
  ispromoted: false,
}
