export const REGIONS: Record<string, string> = {
  AURA: "Auvergne-Rhône-Alpes",
  BOFC: "Bourgogne-Franche-Comté",
  BRET: "Bretagne",
  CVDL: "Centre-Val de Loire",
  GEST: "Grand Est",
  GUA: "Guadeloupe",
  GUY: "Guyane",
  HFRA: "Hauts-de-France",
  LIFB: "Ile-de-France",
  MAR: "Martinique",
  NAQU: "Nouvelle-Aquitaine",
  NCAL: "Nouvelle-Calédonie",
  NORM: "Normandie",
  OCCI: "Occitanie",
  REU: "La Réunion",
  PDLL: "Pays de la Loire",
  PACA: "Provence-Alpes-Côte d’Azur",
}
